### ISSUE TITLE
Unrecognized tag: lasso-head

### ISSUE THREAD

**Issue by hedav85** [lasso-js/lasso-marko#14]
Hello,

I've update my project to the latest version of marko and lasso
* marko 4.7.2
* lasso 3.0.0
* lasso-marko 2.4.0

Now I got the errors that the lasso tags are unknown. The problem is reproducable with the marko-lasso example (https://github.com/marko-js-samples/marko-lasso). The example works with the older version but if you update to the current versions it fails with the "Unrecognized tag error".

Are there any changes how to bootstrap a application with marko + lasso?

**Comment by yomed** [comment]
@hedav85 Make sure to install `@lasso/marko-taglib`, since that was moved to its own package now.

**Comment by austinkelleher** [comment]
Hey @yomed is right. You have to install `@lasso/marko-taglib` to use the latest Marko and Lasso together since we moved the taglib to its own package. I'm going to go ahead and close this out, but feel free to reopen if you have any additional issues.

**Comment by hedav85** [comment]
thank you. Yes I've not installed the @lasso/marko-taglib package. Now it works.

**Comment by charlesread** [comment]
I still ave this issue in a project what uses lasso v3 and @lasso/marko-taglib, if I delete node_modules and `npm i` I get the error, I have to explicitly `npm i @lasso/marko-taglib`, even though @lasso/marko-taglib is a dependency in package.json, to resolve the issue.

**Comment by austinkelleher** [comment]
@charlesread Are you using marko-starter? If so, which version of it?

**Comment by charlesread** [comment]
Hi, @austinkelleher, I am not using `marko-starter`.

**Comment by austinkelleher** [comment]
@charlesread You'll need to manually import the new lasso taglib by adding a `marko.json` in the root of your project.

```
{
    "taglibImports": [
        "@lasso/marko-taglib/marko.json"
    ]
}
```

Let me know if that fixes your issue.

**Comment by charlesread** [comment]
@austinkelleher , sorry for the late response, and thanks for getting back with me. Adding a `marko.json` as you suggested did do the trick, I'm just curious as to why I actually need to do that when I already have `@lasso/marko-taglib` as a dependency.  But this gets the ball over the net, thanks!
