### ISSUE TITLE
Does lasso-marko require lasso (and other questions)?

### ISSUE THREAD

**Issue by basickarl** [lasso-js/lasso-marko#4]
The following code makes me think that `lasso` is a prerequisite dependency for using `lasso-marko`.
```
require('lasso').configure({
    "plugins": [
        ...
        "lasso-marko"
    ]
    ...
});
```

On the other end we have `https://github.com/lasso-js-samples/lasso-marko` and `https://github.com/lasso-js-samples/lasso-templates` which works without having lasso as a dependency.

This is confusing, I understand these are probably different ways of using this plugin, but the documentation has to explain this. I'm also scratching my head as to if I need to install `marko` and `marko-widgets` as separate dependencies to get both of those working.

**Comment by patrick-steele-idem** [comment]
`lasso-marko` is a plugin for `lasso`. So yes, `lasso` is a prerequisite for using `lasso-marko`.

Regarding the [github.com/lasso-js-samples/lasso-templates](https://github.com/lasso-js-samples/lasso-templates) sample app, it uses the [Lasso.js Command Line Interface](https://github.com/lasso-js/lasso#command-line-interface) which requires installing the [lasso-cli](https://www.npmjs.com/package/lasso-cli) package. The [lasso-cli](https://www.npmjs.com/package/lasso-cli) package has an internal dependency on the `lasso` package: [github.com/lasso-js/lasso-cli/package.json#L17](https://github.com/lasso-js/lasso-cli/blob/bcd9e75277a09bb37c7f656acb491a9c65ef5c5e/package.json#L17)

I hope that clears up any confusion.

> I'm also scratching my head as to if I need to install marko and marko-widgets as separate dependencies to get both of those working.

`marko-widgets` is optional and it currently needs to be installed as a separate dependency. We might change that in the future.

I'm going to go ahead and close this issue, but if I didn't answer your question please let me know by posting comments here or feel free to get more clarification in the Gitter chat room for lasso or marko.
